# Generated by Django 5.0.1 on 2024-02-28 12:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('ASB', 'Anti-social behaviour'), ('Roads', 'Road issues'), ('Traffic', 'Traffic issues'), ('Pavements', 'Pavement-related issues'), ('Public spaces maintenance', 'Issues with maintenance of public spaces'), ('Rubbish', 'Rubbish-related issues'), ('Fly-tipping', 'Fly-tipping')], max_length=50),
        ),
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image_uploaded',
            field=models.CharField(blank=True, choices=[('Image uploaded', 'Yes'), ('Image not uploaded', 'No')], max_length=18),
        ),
        migrations.AlterField(
            model_name='issue',
            name='notes_about_notifications',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='IssueType',
        ),
    ]
