# Generated by Django 5.0.1 on 2024-05-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_issue_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='image',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='image_uploaded',
        ),
    ]
