# Generated by Django 5.0.1 on 2024-02-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_issue_image_alter_issue_image_uploaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
